# Generated by Django 5.2.1 on 2025-05-10 00:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RequestLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "source",
                    models.CharField(
                        choices=[("DJANGO", "Django"), ("NGINX", "Nginx")],
                        max_length=10,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("method", models.CharField(blank=True, max_length=10)),
                ("path", models.CharField(max_length=255)),
                ("status_code", models.IntegerField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("referer", models.URLField(blank=True, null=True)),
                (
                    "response_time",
                    models.FloatField(
                        blank=True, help_text="Response time in seconds", null=True
                    ),
                ),
                ("request_body", models.TextField(blank=True, null=True)),
                ("extra_data", models.JSONField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["timestamp"], name="core_reques_timesta_603101_idx"
                    ),
                    models.Index(
                        fields=["source"], name="core_reques_source_11dd43_idx"
                    ),
                    models.Index(
                        fields=["ip_address"], name="core_reques_ip_addr_5f88f4_idx"
                    ),
                    models.Index(
                        fields=["status_code"], name="core_reques_status__03d0e3_idx"
                    ),
                    models.Index(fields=["path"], name="core_reques_path_dee382_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ServerMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("cpu_usage", models.FloatField(help_text="CPU usage percentage")),
                (
                    "memory_usage",
                    models.FloatField(help_text="Memory usage percentage"),
                ),
                ("disk_usage", models.FloatField(help_text="Disk usage percentage")),
                (
                    "network_in",
                    models.FloatField(help_text="Network incoming traffic in KB/s"),
                ),
                (
                    "network_out",
                    models.FloatField(help_text="Network outgoing traffic in KB/s"),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["timestamp"], name="core_server_timesta_e41013_idx"
                    )
                ],
            },
        ),
    ]
