# Generated by Django 5.2.1 on 2025-05-10 00:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("analytics", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FormCorrection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.FloatField()),
                (
                    "segment",
                    models.CharField(
                        choices=[
                            ("HD", "Head"),
                            ("TU", "Upper Torso"),
                            ("TL", "Lower Torso"),
                            ("ALU", "Left Upper Arm"),
                            ("ALL", "Left Lower Arm"),
                            ("ARU", "Right Upper Arm"),
                            ("ARL", "Right Lower Arm"),
                            ("LLU", "Left Upper Leg"),
                            ("LLL", "Left Lower Leg"),
                            ("LRU", "Right Upper Leg"),
                            ("LRL", "Right Lower Leg"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "severity",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Minor"), (2, "Moderate"), (3, "Critical")]
                    ),
                ),
                ("message", models.TextField()),
                ("suggested_cue", models.CharField(max_length=200)),
                (
                    "analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="corrections",
                        to="analytics.exerciseanalysis",
                    ),
                ),
            ],
            options={
                "ordering": ["timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("read", models.BooleanField(default=False)),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("SYSTEM", "System"),
                            ("ACHIEVEMENT", "Achievement"),
                            ("REMINDER", "Reminder"),
                            ("CORRECTION", "Form Correction"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
