services:
  web:
    build: .
    ports:
      - "80:8000"
    environment:
      DJANGO_SETTINGS_MODULE: backend.settings
      SECURE_SSL_REDIRECT: "False"
      ALLOWED_HOSTS_EXTRA: "*.elasticbeanstalk.com,localhost,127.0.0.1"
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000 --workers 2 --timeout 120