# Generated by Django 5.2.1 on 2025-05-10 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("workouts", "0002_exercisetype_remove_workout_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExerciseAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "segment_ranges",
                    models.JSONField(
                        default=dict,
                        help_text="Max angular ranges per segment during movement",
                    ),
                ),
                (
                    "joint_centering",
                    models.JSONField(
                        default=dict, help_text="Joint alignment scores (0-100)"
                    ),
                ),
                (
                    "symmetry_score",
                    models.FloatField(
                        blank=True,
                        help_text="Left/right movement symmetry (0-100)",
                        null=True,
                    ),
                ),
                (
                    "fluidity_score",
                    models.FloatField(
                        blank=True, help_text="Movement smoothness (0-100)", null=True
                    ),
                ),
                (
                    "exercise_set",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis",
                        to="workouts.exerciseset",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BodySegmentPosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.FloatField(help_text="Time in seconds from set start"),
                ),
                (
                    "segment",
                    models.CharField(
                        choices=[
                            ("HD", "Head"),
                            ("TU", "Upper Torso"),
                            ("TL", "Lower Torso"),
                            ("ALU", "Left Upper Arm"),
                            ("ALL", "Left Lower Arm"),
                            ("ARU", "Right Upper Arm"),
                            ("ARL", "Right Lower Arm"),
                            ("LLU", "Left Upper Leg"),
                            ("LLL", "Left Lower Leg"),
                            ("LRU", "Right Upper Leg"),
                            ("LRL", "Right Lower Leg"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "x",
                    models.FloatField(
                        help_text="Left/Right position (0=left, 1=right)"
                    ),
                ),
                (
                    "y",
                    models.FloatField(help_text="Vertical position (0=bottom, 1=top)"),
                ),
                (
                    "z",
                    models.FloatField(
                        help_text="Forward/Back position (0=front, 1=back)"
                    ),
                ),
                ("pitch", models.FloatField(help_text="Nodding angle (degrees)")),
                ("yaw", models.FloatField(help_text="Shaking angle (degrees)")),
                ("roll", models.FloatField(help_text="Tilting angle (degrees)")),
                (
                    "angle_to_parent",
                    models.FloatField(
                        help_text="Angle difference from proximal segment (degrees)"
                    ),
                ),
                (
                    "distance_to_parent",
                    models.FloatField(
                        help_text="Distance from joint to parent segment (normalized)"
                    ),
                ),
                (
                    "exercise_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="segment_positions",
                        to="workouts.exerciseset",
                    ),
                ),
            ],
            options={
                "ordering": ["timestamp"],
                "indexes": [
                    models.Index(
                        fields=["exercise_set", "timestamp"],
                        name="analytics_b_exercis_ebc770_idx",
                    ),
                    models.Index(
                        fields=["segment"], name="analytics_b_segment_2bab84_idx"
                    ),
                ],
            },
        ),
    ]
