# Generated by Django 5.2.1 on 2025-05-10 00:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workouts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExerciseType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("difficulty_level", models.PositiveSmallIntegerField(default=1)),
                ("target_muscles", models.JSONField(default=list)),
                ("form_guidelines", models.TextField(blank=True)),
                ("video_tutorial_url", models.URLField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="workout",
            name="date",
        ),
        migrations.RemoveField(
            model_name="workout",
            name="description",
        ),
        migrations.AddField(
            model_name="workout",
            name="completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="workout",
            name="date_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="workout",
            name="duration",
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workout",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="workout",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="workouts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
                (
                    "workout",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercises",
                        to="workouts.workout",
                    ),
                ),
                (
                    "exercise_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="workouts.exercisetype",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ExerciseSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("set_number", models.PositiveSmallIntegerField()),
                ("reps", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("weight", models.FloatField(blank=True, null=True)),
                ("duration", models.DurationField(blank=True, null=True)),
                ("rest_after", models.DurationField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sets",
                        to="workouts.exercise",
                    ),
                ),
            ],
            options={
                "ordering": ["set_number"],
                "unique_together": {("exercise", "set_number")},
            },
        ),
    ]
