# Generated by Django 5.1.7 on 2025-04-07 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_customuser_height"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="reset_code",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
