# Generated by Django 5.1.7 on 2025-04-04 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_rename_date_of_birth_customuser_dob_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="height",
            field=models.CharField(blank=True, default="0", max_length=10),
        ),
    ]
