# Generated by Django 5.1.7 on 2025-04-04 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_customuser_height"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="height",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
